[2014-10-28 09:01:57] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in C:\xampp\htdocs\laravel_users\bootstrap\compiled.php:4948
Stack trace:
#0 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4790): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4778): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2014-10-28 09:10:53] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\NotFoundHttpException' in C:\xampp\htdocs\laravel_users\bootstrap\compiled.php:4945
Stack trace:
#0 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4790): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\ResourceNotFoundException))
#1 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4778): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2014-10-28 10:38:42] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in C:\xampp\htdocs\laravel_users\bootstrap\compiled.php:4948
Stack trace:
#0 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4790): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4778): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2014-10-28 10:42:18] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in C:\xampp\htdocs\laravel_users\bootstrap\compiled.php:4948
Stack trace:
#0 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4790): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4778): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2014-10-28 10:48:11] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in C:\xampp\htdocs\laravel_users\bootstrap\compiled.php:4948
Stack trace:
#0 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4790): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4778): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2014-10-28 11:06:44] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in C:\xampp\htdocs\laravel_users\bootstrap\compiled.php:4948
Stack trace:
#0 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4790): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4778): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2014-10-28 12:58:15] log.ERROR: exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::group_by()' in C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:1573
Stack trace:
#0 C:\xampp\htdocs\laravel_users\app\controllers\CategoriesController.php(86): Illuminate\Database\Query\Builder->__call('group_by', Array)
#1 C:\xampp\htdocs\laravel_users\app\controllers\CategoriesController.php(86): Illuminate\Database\Query\Builder->group_by('users.id')
#2 [internal function]: CategoriesController->update('2')
#3 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('update', Array)
#5 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4768): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'update', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('2')
#7 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7838): call_user_func_array(Object(Closure), Array)
#8 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7825): Illuminate\Routing\Route->callCallable()
#9 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4779): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2014-10-28 12:58:39] log.ERROR: exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::order_by()' in C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:1573
Stack trace:
#0 C:\xampp\htdocs\laravel_users\app\controllers\CategoriesController.php(86): Illuminate\Database\Query\Builder->__call('order_by', Array)
#1 C:\xampp\htdocs\laravel_users\app\controllers\CategoriesController.php(86): Illuminate\Database\Query\Builder->order_by('id', 'desc')
#2 [internal function]: CategoriesController->update('2')
#3 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('update', Array)
#5 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4768): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'update', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('2')
#7 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7838): call_user_func_array(Object(Closure), Array)
#8 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7825): Illuminate\Routing\Route->callCallable()
#9 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4779): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2014-10-28 12:58:43] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in C:\xampp\htdocs\laravel_users\bootstrap\compiled.php:4948
Stack trace:
#0 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4790): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4778): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2014-10-28 12:59:19] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in C:\xampp\htdocs\laravel_users\bootstrap\compiled.php:4948
Stack trace:
#0 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4790): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4778): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2014-10-28 12:59:22] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in C:\xampp\htdocs\laravel_users\bootstrap\compiled.php:4948
Stack trace:
#0 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4790): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4778): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2014-10-28 12:59:28] log.ERROR: exception 'BadMethodCallException' with message 'Call to undefined method Illuminate\Database\Query\Builder::group_by()' in C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php:1573
Stack trace:
#0 C:\xampp\htdocs\laravel_users\app\controllers\CategoriesController.php(86): Illuminate\Database\Query\Builder->__call('group_by', Array)
#1 C:\xampp\htdocs\laravel_users\app\controllers\CategoriesController.php(86): Illuminate\Database\Query\Builder->group_by('users.id')
#2 [internal function]: CategoriesController->update('2')
#3 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#4 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('update', Array)
#5 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4768): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'update', Array)
#6 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('2')
#7 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7838): call_user_func_array(Object(Closure), Array)
#8 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7825): Illuminate\Routing\Route->callCallable()
#9 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4779): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#10 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#12 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#13 {main} [] []
[2014-10-28 13:00:13] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in C:\xampp\htdocs\laravel_users\bootstrap\compiled.php:4948
Stack trace:
#0 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4790): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4778): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2014-10-28 13:07:07] log.ERROR: exception 'Exception' with message 'SQLSTATE[42S22]: Column not found: 1054 Unknown column 'email' in 'where clause' (SQL: select count(*) as aggregate from `categories` where `email` is null and `id` != ?) (Bindings: array (
  0 => '2',
))' in C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Database\Connection.php:502
Stack trace:
#0 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Database\Connection.php(475): Illuminate\Database\Connection->handleQueryException(Object(PDOException), 'select count(*)...', Array)
#1 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Database\Connection.php(269): Illuminate\Database\Connection->run('select count(*)...', Array, Object(Closure))
#2 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(966): Illuminate\Database\Connection->select('select count(*)...', Array)
#3 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(956): Illuminate\Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(943): Illuminate\Database\Query\Builder->getFresh(Array)
#5 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1283): Illuminate\Database\Query\Builder->get(Array)
#6 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Database\Query\Builder.php(1225): Illuminate\Database\Query\Builder->aggregate('count', Array)
#7 C:\xampp\htdocs\laravel_users\app\controllers\CategoriesController.php(69): Illuminate\Database\Query\Builder->count()
#8 [internal function]: CategoriesController->edit('2')
#9 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#10 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('edit', Array)
#11 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4768): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'edit', Array)
#12 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('2')
#13 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7838): call_user_func_array(Object(Closure), Array)
#14 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7825): Illuminate\Routing\Route->callCallable()
#15 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4779): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#16 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#17 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#18 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#19 {main} [] []
[2014-10-28 13:25:53] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in C:\xampp\htdocs\laravel_users\bootstrap\compiled.php:4948
Stack trace:
#0 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4790): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4778): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2014-10-28 14:23:37] log.ERROR: exception 'Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException' in C:\xampp\htdocs\laravel_users\bootstrap\compiled.php:4948
Stack trace:
#0 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4790): Illuminate\Routing\Router->handleRoutingException(Object(Symfony\Component\Routing\Exception\MethodNotAllowedException))
#1 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4778): Illuminate\Routing\Router->findRoute(Object(Illuminate\Http\Request))
#2 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#3 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#4 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#5 {main} [] []
[2014-10-28 14:27:30] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function getClientOriginalExtension() on a non-object' in C:\xampp\htdocs\laravel_users\app\controllers\HomeController.php:111
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2014-10-28 14:29:09] log.ERROR: exception 'Symfony\Component\Debug\Exception\FatalErrorException' with message 'Call to a member function getClientOriginalExtension() on a non-object' in C:\xampp\htdocs\laravel_users\app\controllers\HomeController.php:111
Stack trace:
#0 [internal function]: Illuminate\Exception\Handler->handleShutdown()
#1 {main} [] []
[2014-10-28 14:31:35] log.ERROR: exception 'ErrorException' with message 'Undefined index: qual' in C:\xampp\htdocs\laravel_users\app\controllers\HomeController.php:100
Stack trace:
#0 C:\xampp\htdocs\laravel_users\app\controllers\HomeController.php(100): Illuminate\Exception\Handler->handleError(8, 'Undefined index...', 'C:\\xampp\\htdocs...', 100, Array)
#1 [internal function]: HomeController->postRegister()
#2 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('postRegister', Array)
#4 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4768): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'postRegister', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#6 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7838): call_user_func_array(Object(Closure), Array)
#7 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7825): Illuminate\Routing\Route->callCallable()
#8 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4779): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2014-10-28 16:05:13] log.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' in C:\xampp\htdocs\laravel_users\bootstrap\compiled.php:5430
Stack trace:
#0 C:\xampp\htdocs\laravel_users\app\controllers\CategoriesController.php(67): Illuminate\Database\Eloquent\Model::findOrFail(1)
#1 [internal function]: CategoriesController->edit('2')
#2 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('edit', Array)
#4 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4768): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'edit', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('2')
#6 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7838): call_user_func_array(Object(Closure), Array)
#7 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7825): Illuminate\Routing\Route->callCallable()
#8 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4779): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2014-10-28 16:05:34] log.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' in C:\xampp\htdocs\laravel_users\bootstrap\compiled.php:5430
Stack trace:
#0 C:\xampp\htdocs\laravel_users\app\controllers\CategoriesController.php(67): Illuminate\Database\Eloquent\Model::findOrFail(2)
#1 [internal function]: CategoriesController->edit('2')
#2 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('edit', Array)
#4 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4768): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'edit', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('2')
#6 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7838): call_user_func_array(Object(Closure), Array)
#7 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7825): Illuminate\Routing\Route->callCallable()
#8 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4779): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2014-10-28 16:05:43] log.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' in C:\xampp\htdocs\laravel_users\bootstrap\compiled.php:5430
Stack trace:
#0 C:\xampp\htdocs\laravel_users\app\controllers\CategoriesController.php(67): Illuminate\Database\Eloquent\Model::findOrFail(2)
#1 [internal function]: CategoriesController->edit('3')
#2 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('edit', Array)
#4 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4768): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'edit', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('3')
#6 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7838): call_user_func_array(Object(Closure), Array)
#7 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7825): Illuminate\Routing\Route->callCallable()
#8 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4779): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2014-10-28 16:07:45] log.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' in C:\xampp\htdocs\laravel_users\bootstrap\compiled.php:5430
Stack trace:
#0 C:\xampp\htdocs\laravel_users\app\controllers\CategoriesController.php(67): Illuminate\Database\Eloquent\Model::findOrFail(5)
#1 [internal function]: CategoriesController->edit('3')
#2 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('edit', Array)
#4 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4768): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'edit', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('3')
#6 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7838): call_user_func_array(Object(Closure), Array)
#7 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7825): Illuminate\Routing\Route->callCallable()
#8 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4779): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2014-10-28 16:07:55] log.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' in C:\xampp\htdocs\laravel_users\bootstrap\compiled.php:5430
Stack trace:
#0 C:\xampp\htdocs\laravel_users\app\controllers\CategoriesController.php(67): Illuminate\Database\Eloquent\Model::findOrFail(5)
#1 [internal function]: CategoriesController->edit('3')
#2 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('edit', Array)
#4 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4768): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'edit', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('3')
#6 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7838): call_user_func_array(Object(Closure), Array)
#7 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7825): Illuminate\Routing\Route->callCallable()
#8 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4779): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
[2014-10-28 16:07:59] log.ERROR: exception 'Illuminate\Database\Eloquent\ModelNotFoundException' in C:\xampp\htdocs\laravel_users\bootstrap\compiled.php:5430
Stack trace:
#0 C:\xampp\htdocs\laravel_users\app\controllers\CategoriesController.php(67): Illuminate\Database\Eloquent\Model::findOrFail(5)
#1 [internal function]: CategoriesController->edit('3')
#2 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(138): call_user_func_array(Array, Array)
#3 C:\xampp\htdocs\laravel_users\vendor\laravel\framework\src\Illuminate\Routing\Controllers\Controller.php(115): Illuminate\Routing\Controllers\Controller->callMethod('edit', Array)
#4 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4768): Illuminate\Routing\Controllers\Controller->callAction(Object(Illuminate\Foundation\Application), Object(Illuminate\Routing\Router), 'edit', Array)
#5 [internal function]: Illuminate\Routing\Router->Illuminate\Routing\{closure}('3')
#6 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7838): call_user_func_array(Object(Closure), Array)
#7 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(7825): Illuminate\Routing\Route->callCallable()
#8 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(4779): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#9 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(483): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#10 C:\xampp\htdocs\laravel_users\bootstrap\compiled.php(472): Illuminate\Foundation\Application->dispatch(Object(Illuminate\Http\Request))
#11 C:\xampp\htdocs\laravel_users\public\index.php(49): Illuminate\Foundation\Application->run()
#12 {main} [] []
